import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="w-full">
            <div className="max-w-5gxl max-auto px-6 md:px-12 xl:px-6">
              <div className="flex flex-wrap items-center justify-between">
                <div>Logo</div>
                <div>
                  <ul className="flex flex-rowd gap-6">
                    <li>Home</li>
                    <li>About</li>
                    <li>Contact</li>
                    <li>Work</li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </header>
        <main>{children}</main>
        </body>
    </html>
  );
}